=== Sanjanah8/Web-technology/My LAB/XML/extern.dtd
<!ELEMENT document (customer)*>
<!ELEMENT customer (name,date,orders)>
<!ELEMENT name (firstname,lastname)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT orders (item)*>
<!ELEMENT item (product,number,price)>
<!ELEMENT product (#PCDATA)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT price (#PCDATA)>

=== Sanjanah8/Web-technology/My LAB/XML/cust.xml
<?xml version="1.0"?>
<!DOCTYPE document SYSTEM "extern.dtd">
<document>
<customer>
<name>
<firstname>aaa</firstname>
<lastname>bbb</lastname>
</name>
<date>1 jan 2021</date>
<orders>
<item>
<product>chocolates</product>
<number>666</number>
<price>250</price>
</item>


 
 

 
<item>
 

<product>sweets</product>
<number>777</number>
<price>450</price>
 
</item>
</orders>
</customer>
</document>
 
 

</CUSTOMER>
</DOCUMENT>
